services:
  sillytavern:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - TZ=[TimeZone]
    expose:
      - 8000
    volumes:
      - "../../files/plugins:/home/node/app/plugins"
      - "../../files/config:/home/node/app/config"
      - "../../files/data:/home/node/app/data"
    restart: unless-stopped
